spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.jdbc.log.errors: true

server:
  shutdown: graceful

logging:
  level:
    root: INFO
    com.mogumogu.momogo: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

momogo:
  openapi:
    server-url: https://api.dev.mogumogo.com
  app-version:
    ios:
      latest-version: 1.0.0
      min-supported-version: 1.0.0
      update-url: https://apps.apple.com/app/id000000000
    android:
      latest-version: 1.0.0
      min-supported-version: 1.0.0
      update-url: https://play.google.com/store/apps/details?id=com.mogumogu.momogo
